[package]
name = "rust-hi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.metalos]
path = "..\\..\\crates\\metalos"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"